### PR TITLE
fix: use `axum-client-ip` to get the real client IP

### LINKED ISSUE #225: fix: geoip lookup errors for the grey IP networks
We have a lot of following errors:
```
2023-09-29T13:37:14.085015Z ERROR geoip lookup error: AddressNotFoundError: Address not found in database
```
reflecting that we are querying the geoip database with the non-existent (internal grey networks) IPs.
As a solution, we should use `X-Forwarded-For` header as a client IP source and skip the lookup in case it's absent.

### PR DESCRIPTION
**Pull request by geekbrother**
# Description

This PR adds using of `axum-client-ip` to get a real client IP which is included in the `X-Forwarded` by calling `SecureClientIp`. The AWS ELB[ uses X-Forwarded-for](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html) and [SecureClientIp sourced it for a real IP](https://github.com/imbolc/axum-client-ip/blob/a23f172ee4d01ead9ec25cedd3e6359ba63a03ad/src/secure.rs#L33).

Following changes are made:
 - `axum-client-ip` is added to the `Cargo.toml` as a dependency. We [already have it](https://github.com/WalletConnect/echo-server/blob/46d17972c3f83288fd849ca4c16ad15edb11caee/Cargo.lock#L607) as a relative dependency in the `Cargo.lock` so it will not add additional dependency weight.
 - `ConnectInfo` replaced with `SecureClientIp`.

Resolves #225

## How Has This Been Tested?

Successfully built and run with `analytics` feature enabled.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by chris13524 — APPROVED** [review]
LGTM

**Comment by arein** [comment]
Nice vendor agnostic solution!

**Review by arein — APPROVED** [review]

File: src/lib.rs [hunk 1]
```diff
@@ -210,7 +211,8 @@ pub async fn bootstap(mut shutdown: broadcast::Receiver<()>, config: Config) ->
                     hyper::http::header::CONTENT_TYPE,
                     hyper::http::header::AUTHORIZATION,
                 ]),
-        );
+        )
+        .layer(SecureClientIpSource::ConnectInfo.into_extension());
```
Comment (chris13524) [inline src/lib.rs]:
```suggestion
        .layer(SecureClientIpSource::RightmostXForwardedFor.into_extension());
```

**Review by chris13524 — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 1 above)
Comment (geekbrother) [reply src/lib.rs]: Good catch! Thanks, Chris. Applied it.

**Review by chris13524 — APPROVED** [review]
