### PR TITLE
chore: fix byzantine failures on functional tests

### LINKED ISSUE #205: chore: byzantine faults in CI functional unit tests
When functional unit tests are on there are byzantine faults that occur sometimes: sometimes functional tests fail and pass successfully after a re-run of the CI workflow.
I assume that's because there are no cleanups after each test. 
Also, to track the error messages we should remove `assert!(***.is_ok())` and change to `unwrap()`, because when unwrap panic occurs it prints the complete error information.

### PR DESCRIPTION
**Pull request by geekbrother**
# Description

To fix byzantine failures on functional tests following changes are made:
- Make `TOKEN` [unique for each test](https://github.com/WalletConnect/echo-server/pull/206/commits/7a8fc2c50084803ee3e485dc127457377b98188a) for running tests in parallel and prevent data race conditions in the test PG database,
- Fixing warnings in functional unit tests [about unused variables](https://github.com/WalletConnect/echo-server/pull/206/commits/047facd9091faf4a8e75d4537c32da8d06d473c1).

Resolves #205

## How Has This Been Tested?

Automatically tests by the CI unit test workflow by iterating it 3-5 times.
The expected result is passing the CI unit tests all of the time.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: tests/functional/stores/client.rs [hunk 1]
```diff
@@ -7,72 +7,77 @@ use {
...
-            token: TOKEN.to_string(),
+            token,
         })
-        .await;
-
-    assert!(res.is_ok())
+        .await
+        .unwrap();
+    // Cleaning up records
+    ctx.clients.delete_client(TENANT_ID, &id).await.unwrap();
```
Comment (chris13524) [inline tests/functional/stores/client.rs:24]: Any concern if the `unwrap()` fails and then the records don't get cleaned up?

**Review by chris13524 — APPROVED** [review]

File: tests/functional/stores/client.rs (hunk 1 above)
Comment (geekbrother) [reply tests/functional/stores/client.rs:24]: We are spinning new PostgreSQL docker instances each time we are running the unit tests, so records from the old run should be wiped anyway. I've changed the `TOKEN` to become unique for every test case to fix cases when one case fails/unwrap and solve the domino effect as every case has its own TOKEN in the database table. The main issue was that there was one constant TOKEN for all cases that led to the domino effect and race effect in case run tests in parallel.
