### PR TITLE
fix: fixing and enabling ignored tests

### LINKED ISSUE #264: test: enabling and fixing ignored tests
Functional tests for creating and deleting tenants and updating fcm key are ignored.
They should be fixed for the run and turned on as we don't have integration tests for these handlers.

### PR DESCRIPTION
**Pull request by geekbrother**
# Description

Fixing for running and removing ignore for the following tests:
- Updating fcm with the valid API key,
- Register, get, and delete new tenants.

Resolves #264 

## How Has This Been Tested?

Tests are run by the CI unit tests workflow and passing it:
- [tenant_update_fcm_valid](https://github.com/WalletConnect/echo-server/actions/runs/6611285586/job/17957940496?pr=263#step:11:863),
- [tenant_register_get_delete](https://github.com/WalletConnect/echo-server/actions/runs/6611285586/job/17957940496?pr=263#step:11:861).

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: tests/functional/multitenant/tenancy.rs [hunk 1]
```diff
@@ -1,34 +1,47 @@
...
+        &EncodingKey::from_secret(ctx.config.jwt_secret.as_bytes()),
+    )
+    .expect("Failed to encode jwt token");
 
     // Register tenant
     let client = reqwest::Client::new();
     let response = client
         .post(format!("http://{}/tenants", ctx.server.public_addr))
         .json(&payload)
+        .header("AUTHORIZATION", jwt_token.clone())
```
Comment (chris13524) [inline tests/functional/multitenant/tenancy.rs:40]: I'm confused, were these tests failing before? Why is there no associated source code change?

Comment (chris13524) [reply tests/functional/multitenant/tenancy.rs:40]: Should these tests be added to https://github.com/WalletConnect/echo-server/pull/261 instead?

**Review by arein — APPROVED** [review]
awesome

**Review by chris13524 — APPROVED** [review]
