### PR TITLE
fix(cors-headers): allow authorization and content-type headers

### LINKED ISSUE #87: feat: CORS headers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some CORS headers are missing which makes it impossible to make requests from browsers.
`Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response`

### Requested Behavior

Add CORS headers so that we can make requests from browsers

### Anything else?

See example [here](https://www.stackhawk.com/blog/rust-cors-guide-what-it-is-and-how-to-enable-it/)

### PR DESCRIPTION
**Pull request by Cali93**
# Description

Resolves #87

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -187,7 +187,11 @@ pub async fn bootstap(mut shutdown: broadcast::Receiver<()>, config: Config) ->
                                 .iter()
                                 .map(|v| v.parse::<HeaderValue>().unwrap())
                                 .collect::<Vec<HeaderValue>>(), */
-                        .allow_origin(AllowOrigin::any()),
+                        .allow_origin(AllowOrigin::any())
+                        .allow_headers(vec![
+                            "Content-Type".parse().unwrap(),
+                            "Authorization".parse().unwrap(),
+                        ]),
```
Comment (Rakowskiii) [inline src/lib.rs]:
```suggestion
                        .allow_headers([hyper::http::header::CONTENT_TYPE, hyper::http::header::AUTHORIZATION]),
```

Comment (Rakowskiii) [reply src/lib.rs]: I think this would be a cleaner way to do it 😄

**Review by Rakowskiii — APPROVED** [review]

**Review by HarryET — CHANGES_REQUESTED** [review]
Why is the lock file updated in this PR? Otherwise looks good! 😁
