### PR TITLE
fix: revert to the base64 encoded p8 key

### LINKED ISSUE #244: bug: APNS certificate validation errors
There is an error when using p12 certificate without a password for the APNS.
Context: https://walletconnect.slack.com/archives/C03RU4F6P8A/p1697184620615089

The following error occurs when validating the p8 certificate:
```
[Expecting: ANY PRIVATE KEY"](library: "PEM routines", function: "get_name", reason: "no start line", file: "../crypto/pem/pem_lib.c", line: 745, data: "Expecting: ANY PRIVATE KEY")
```

### PR DESCRIPTION
**Pull request by geekbrother**
# Description

This PR reverting back to double base64 encoding for the p8 apns key.
As the p8 key is already in the PEM (base64) format we used the base64 encoded key before #246 and to prevent confusion and make a proper migration - reverting back to the base64 encoded PEM format.

Additional tracing logs are also added in this PR.

Resolves #244 

## How Has This Been Tested?

p8 key validation is tested by [tenant_update_apns_valid_token](https://github.com/WalletConnect/echo-server/blob/main/tests/functional/multitenant/apns.rs#L62) unit test in the CI gate.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/stores/tenant.rs [hunk 1]
```diff
@@ -218,9 +219,15 @@ impl Tenant {
                         &self.apns_team_id,
                     ) {
                         (Some(topic), Some(pkcs8_pem), Some(key_id), Some(team_id)) => {
-                            let mut reader = BufReader::new(pkcs8_pem.as_bytes());
+                            info!("apns token (p8) provider is matched");
+                            // For supporting the legacy format of the p8 key which is double base64 encoded
```
Comment (chris13524) [inline src/stores/tenant.rs]: If it's "double" base64 encoded, then won't decoding always pass?

**Review by chris13524 — CHANGES_REQUESTED** [review]

File: src/stores/tenant.rs (hunk 1 above)
Comment (geekbrother) [reply src/stores/tenant.rs]: The updated p8 key format in the database is plain text like:
```
-----BEGIN PRIVATE KEY-----
...base64 encoded key...
-----END PRIVATE KEY-----
```
which is actually the content of the p8 key file.

The legacy format was that content but encoded in base64 with the `BEGIN/END PRIVATE KEY` header and footer.
So the new format should not be decoded successfully (because of the header and footer) and we should pass the plain text instead in `unwrap_or`.

We should encode p12 because it's content is in bytes, but skip for further "double" encoding p8.

Comment (geekbrother) [reply src/stores/tenant.rs]: Resolving this as we've decided to go back to the base64 encoded PEM key for p8.

File: src/stores/tenant.rs [hunk 2]
```diff
@@ -218,9 +218,12 @@ impl Tenant {
                         &self.apns_team_id,
                     ) {
                         (Some(topic), Some(pkcs8_pem), Some(key_id), Some(team_id)) => {
-                            let mut reader = BufReader::new(pkcs8_pem.as_bytes());
+                            info!("apns token (p8) provider is matched");
+                            let p8_token = base64::engine::general_purpose::STANDARD
+                                .decode(pkcs8_pem)
+                                .expect("p8 token is not a valid base64 string");
```
Comment (chris13524) [inline src/stores/tenant.rs]: Use `?` instead of `.expect()`

**Review by chris13524 — CHANGES_REQUESTED** [review]

File: src/stores/tenant.rs (hunk 2 above)
Comment (geekbrother) [reply src/stores/tenant.rs]: When using `?` here we will miss the context, if we use `expect` we can pass additional context right to the error, so the error will be like `p8 token is not a valid base64 string: Bad character at $%!`.

Comment (geekbrother) [reply src/stores/tenant.rs]: Removing it because this can't be handled properly in this behavior ((

**Review by chris13524 — APPROVED** [review]
