### PR TITLE
fix: data only messages not showing in background

### LINKED ISSUE #187: fix: data only messages not showing in background

### PR DESCRIPTION
**Pull request by chris13524**
# Description

See: https://walletconnect.slack.com/archives/C044SKFKELR/p1694013173081069?thread_ts=1693998479.953179&cid=C044SKFKELR

Resolves #187

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/providers/fcm.rs [hunk 1]
```diff
@@ -39,6 +39,9 @@ impl PushProvider for FcmProvider {
 
         let result = if payload.is_encrypted() {
             message_builder.data(&payload)?;
+            // Must set priority=high on data-only messages or they don't show unless app is
+            // active: https://rnfirebase.io/messaging/usage#data-only-messages
+            message_builder.priority(Priority::High);
```
Comment (Cali93) [inline src/providers/fcm.rs:46]: Can you also cover the case for iOS ?
We need to set `contentAvailable: true`

https://rnfirebase.io/messaging/usage#data-only-messages

**Review by Cali93 — APPROVED** [review]
LGTM if we also cover the case for iOS

**Review by arein — APPROVED** [review]
